# xprespay/docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: xprespay_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: xprespay
      POSTGRES_PASSWORD: xprespay_secret
      POSTGRES_MULTIPLE_DATABASES: xprespay_db,keycloak_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgres-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
    ports:
      - "5432:5432"
    networks:
      - xprespay_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: xprespay_keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: xprespay
      KC_DB_PASSWORD: xprespay_secret
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - xprespay_net

volumes:
  postgres_data:

networks:
  xprespay_net:
    driver: bridge